PACKAGE_NAME="morse-fgh100m"
PACKAGE_VERSION="1.16.4"

BUILT_MODULE_NAME[0]="morse"
BUILT_MODULE_NAME[1]="dot11ah"

DEST_MODULE_LOCATION[0]="/kernel/drivers/net/wireless/fgh100m/"
DEST_MODULE_LOCATION[1]="/kernel/drivers/net/wireless/fgh100m/dot11ah/"

MAKE[0]="make KSRC=/lib/modules/${kernelver}/build KERNEL_SRC=/lib/modules/${kernelver}/build"
CLEAN="make clean KSRC=/lib/modules/${kernelver}/build KERNEL_SRC=/lib/modules/${kernelver}/build"

AUTOINSTALL="yes"
